//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace business.ui.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("business.ui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;RSAKeyValue&gt;&lt;Modulus&gt;1FTNn5RuTl9+E2AaTP9TnMoH8UkoIXoGYJRN8LlHaT2tUmpyGK+3J+FuY1/HNWZ6qm8lokVClqRiKzGU5c0AjK3swvYbqWTIiAkQbSr5pQ3kEU+gGkQPAjeLhhkV31t7PAsuR02Ujs4SKieLBUKx1Rad3tP7uIPzQsbyl8ydUUE=&lt;/Modulus&gt;&lt;Exponent&gt;AQAB&lt;/Exponent&gt;&lt;P&gt;+/MBI8DodrFfaht5ZtHLcExnSEKPjHX55yVzQE4jXLoNUAcs1vt80ncZCz1NKrmWTV96vceJIxOFHXn8eAFnow==&lt;/P&gt;&lt;Q&gt;1768Sm2JA68LuPNvjqscS6AnZYxs7/98b9Avs2PjB8txBYhPa2ZklcGc9zVjXjU8OKiQC/Gi+nIh49QGWQ2Byw==&lt;/Q&gt;&lt;DP&gt;5Kjz9NYEZIywMuXCda2b/ExrRCqci3cbGkxj4A3KjEKTCHmqmWZfL8hFY2z8VvVeUtR/2jN44+u4WTs4BlYIDw==&lt; [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string _private {
            get {
                return ResourceManager.GetString("_private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;RSAKeyValue&gt;&lt;Modulus&gt;1FTNn5RuTl9+E2AaTP9TnMoH8UkoIXoGYJRN8LlHaT2tUmpyGK+3J+FuY1/HNWZ6qm8lokVClqRiKzGU5c0AjK3swvYbqWTIiAkQbSr5pQ3kEU+gGkQPAjeLhhkV31t7PAsuR02Ujs4SKieLBUKx1Rad3tP7uIPzQsbyl8ydUUE=&lt;/Modulus&gt;&lt;Exponent&gt;AQAB&lt;/Exponent&gt;&lt;/RSAKeyValue&gt;.
        /// </summary>
        public static string _public {
            get {
                return ResourceManager.GetString("_public", resourceCulture);
            }
        }
    }
}
